services:
  - type: web
    name: oxaam-scraper-api
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m playwright install --with-deps chromium
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 240 app:app
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0
